spring:
  application.name: hhplus-tdd
  
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: 
    password: 

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    root: DEBUG